import MiniCompiler.AST
import MiniCompiler.Passes.Shrink
import MiniCompiler.Passes.Uniquify
import MiniCompiler.Passes.UncoverGet
import MiniCompiler.Passes.FreeVars
import MiniCompiler.Passes.ConvertAssignments
import MiniCompiler.Passes.ConvertToClosures
import MiniCompiler.Passes.RevealFunctions
import MiniCompiler.Passes.LimitFunctions
import MiniCompiler.Passes.RCO
import MiniCompiler.Passes.ExplicateControl
import MiniCompiler.Passes.SelectInstructions
import MiniCompiler.Passes.AssignHomes
import MiniCompiler.Passes.PatchInstructions
import MiniCompiler.Passes.PreludeConclusion
import MiniCompiler.Passes.Liveness
import MiniCompiler.Passes.Interference
import MiniCompiler.Passes.GraphColoring
import MiniCompiler.Passes.TypeChecker
import MiniCompiler.Passes.Tagging
import MiniCompiler.Passes.CastInsert
import MiniCompiler.Passes.RevealCasts
